### ISSUE TITLE
No logging output

### ISSUE THREAD

**Issue by markusstephanides** [ndelvalle/rustapi#122]
Hi, first of all: Thanks for this template, really helps getting started fast with APIs!

If I clone this repository, start a mongo db server and then start the API binary, it starts, creates the collections in the database but doesn't yield any output from the logging macros you used, only from axum.
According to the source code of  `main.rs` and the line `info!("listening on {}", &address);`, I should atleast get that message.

Is this intended?

**Comment by ndelvalle** [comment]
Hi @markusstephanides, no this is not intended, indeed you should get the “listening on” message.

Are you cloning the project now? Or is it an old clone? I'm asking because I fixed an issue like this one in the past.
Are you updating the config? Or is it a clean clone?
You said that you had started MongoDB, so I guess this is not the issue. I'm bringing this up because if you don't start MongoDB and you start the API there is no message for a while until a MongoDB error is thrown.

I'm trying to reproduce it, but I can't (Unless I stop MongoDB). This is what I got using a clean clone, starting MongoDB and running `cargo run`:

<img width="717" alt="Screen Shot 2022-08-23 at 10 00 27" src="https://user-images.githubusercontent.com/6719053/186164393-c0f2c8cf-829c-40fd-be3f-eddd5773de7f.png">

**Comment by markusstephanides** [comment]
Hi, I'm sorry it seems like I didn't have a clean clone. I think my issue could be correlated with changing the name of the binary crate. Is there something else I have to change so it works?

**Comment by ndelvalle** [comment]
Yeah, check the name of the crate [here](https://github.com/ndelvalle/rustapi/blob/master/Cargo.toml#L2), then check the logger setup [here](https://github.com/ndelvalle/rustapi/blob/master/src/logger.rs#L9) and change `rustapi` with your crate name. Let me know if that works for you.
I should probably update the logger to read the crate name dynamically.

**Comment by markusstephanides** [comment]
Yes that helped! The main problem was that my crate had dashes instead of underscores as name which seemed to be the problem why I got no logging output. Thank you very much!
